# .github/workflows/ci.yml

name: KlinikOps CI Pipeline

on:
  push:
    branches: [ main, develop ] # 'main' veya 'develop' branch'ine push yapinca tetiklenir
  pull_request:
    branches: [ main ]         # 'main' branch'ine pull request acilinca tetiklenir

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Her zaman standart bir ortamda (Ubuntu) calisir
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3 # 1. Adim: Kodu GitHub runner'ina indirir

    - name: Set up Python
      uses: actions/setup-python@v4 # 2. Adim: Python'u kurar
      with:
        python-version: '3.11' # Ortamimizla ayni versiyonu kullaniyoruz

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # 3. Adim: requirements.txt'deki tum kutuphaneleri kurar
        
    - name: Lint with flake8
      run: |
        # 4. Adim: Kod kalitesini (PEP8) kontrol eder
        # --count -> hatalari say
        # --select=E9,F63,F7,F82 -> bazi hatalari goster
        # --show-source -> hatali kodu goster
        # --statistics -> istatistikleri goster
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
   
    - name: Test with pytest
      # 'PYTHONPATH' ortam değişkenini ekliyoruz.
      # Bu değişken, Python'a projenin kök dizinini ('.') arama yolu olarak gösterir.
      env:
        PYTHONPATH: .
      run: |
        # 5. Adim: 'tests' klasorundeki tum testleri calistirir
        pytest
